### ISSUE TITLE
Not watching Sass files in sub-directories under src/sass/

### ISSUE THREAD

**Issue by chibicode** [greypants/gulp-starter#101]
Looks like `watch.js` is only watching sass files that are directly under the `sass` directory but not any of its subdirectories. So when I made a subdirectory under `sass` containing Sass partial files, they were not reloaded on save.

- https://github.com/greypants/gulp-starter/blob/d7fdb1bb6396b484ce784755ac7413954ee73f1a/gulp/tasks/watch.js#L10
- https://github.com/greypants/gulp-starter/blob/d7fdb1bb6396b484ce784755ac7413954ee73f1a/gulp/config.js#L12

I guess you're not using `**` because of performance reasons, but it'd be useful if it can watch subdirectories as well.

**Comment by greypants** [comment]
good catch. Thanks. Will fix.

**Comment by chibicode** [comment]
:+1: thanks!

**Comment by lcb931023** [comment]
This generates an error from `gulp-sass` for [my project](github.com/lcb931023/bartholomew):
```
[gulp-sass] invalid property name on line 10 in /Users/changbaili/Sites/bartholomew/src/sass/vendor/jquery.pagepiling.scss
```

Seems to be a `libsass` / `gulp-sass` [error](https://github.com/dlmanning/gulp-sass/issues/40#issuecomment-73445421)?

adding `errLogToConsole: true` is a workaround, but that disables the sass error notification.
