### ISSUE TITLE
Solution to "require" css in sass

### ISSUE THREAD

**Issue by ValeryVS** [greypants/gulp-starter#109]
How to include css file in sass to get one output file and not break sourcemap?
I use two files now, one with sass and second with .css import.
For second file I use "gulp-cssimport".
And for production version, when sourcemap not needed, these files can be concatenated.

Is there any better solution? Some browserify for css or sprockets require syntax?

**Comment by pixeleet** [comment]
css is valid sass you could just import it as if it was sass? ;)

**Comment by ValeryVS** [comment]
@import "file.css"
will be compiled to css import tag,
but I want to include content of file.css to one file.

**Comment by ValeryVS** [comment]
And renaming to scss isnt very comfortable when using vendor components.

**Comment by ValeryVS** [comment]
Found a way
- create css file with @import requirements
- use "gulp-cssimport" on it
- use "gulp-rename" to rename file in stream to file to .scss
- store it in generated folder
- import generated scss file in main sass file, it will be concatenated as other and sourcemap works

Imported css files are from vendor components, so I'm not realy care of getting real sourcemap for them, concatenated file is ok.

It works, but may be there are cleaner way? Without generating scss file from requirements.

My experiments are there
https://github.com/ValeryVS/gulp-blank-project

**Comment by synapticism** [comment]
This is a very common problem: https://github.com/sass/sass/issues/556

Personally I just copy, rename, and import as SCSS.

**Comment by deefour** [comment]
@ValeryVS You could just write a [`postinstall`](https://docs.npmjs.com/misc/scripts) command in your `package.json` to copy the `.css` file to `.scss` within it's source folder.

**Comment by greypants** [comment]
Yeah, I tend to just change the extension to `.scss` as well. Valid css is valid scss, so there's no harm.
