### ISSUE TITLE
Reasons for using Swig?

### ISSUE THREAD

**Issue by KingScooty** [greypants/gulp-starter#115]
Just curious what the reasons for using Swig over something like Assemble are in `v2.0`. For the case of this project, Swig seems to be used as a static html generator, but it's not setup to accept data files to generate multiple html files from one swig template. For instance:

Swig template:
-  pages.html

Pages data (either markdown or json):
-  home{.md, .json}
-  about{.md, .json}
-  contact{.md, .json}

Ideally, the outcome would be 3x html files based off the `pages.html` template, for each of the data files (`home.html`, `about.html`, `contact.html`) 

Is this possible with swig?

**Comment by greypants** [comment]
Good question. Integrating data is on my mental to-do list (i should make an actual issue). The gulp-swig docs refer to [gulp-data](https://www.npmjs.com/package/gulp-data) for handling this.

I chose swig because I'm familiar with Twig (what's used on Craft CMS), and it feels more powerful than Handlebars. If you can make a good case for Assemble, I'd consider it. I'll look into it if I get some time.

But either way, you're right. Definitely want to be able to handle data externally.

**Comment by KingScooty** [comment]
Yeah, i was looking into getting [gulp-data](https://www.npmjs.com/package/gulp-data) setup with this branch, but there seems to be a 1:1 relationship with templates and data. I can't seem to figure out how to setup a collection with swig, so you can have a many:1 relationship (data files to one template). I must be missing something, though as i'm sure the devs would have realised this isn't very DRY.

Swig certainly feels more powerful than Handlebars though, and Assemble uses Handlebars, but if we can't generate multiple html files from one template and multiple data files, then that sucks a bit :(

**Comment by rstormsf** [comment]
why not jade?

**Comment by mnokeefe** [comment]
Another vote for Jade. Swig is the only downside to gulp-starter for me.

**Comment by jontron** [comment]
+3 for Jade support.

**Comment by rstormsf** [comment]
https://github.com/raptorjs/marko - just watched these 3:
http://knowthen.com/episode-6-serving-content-in-koajs-with-jade/
http://knowthen.com/episode-8-serving-content-in-koajs-with-marko/
http://knowthen.com/episode-7-serving-content-in-koajs-with-swig/

So looks like Marko is winner.

**Comment by greypants** [comment]
https://github.com/greypants/gulp-starter/issues/154
