### ISSUE TITLE
Sourcemaps not generated?

### ISSUE THREAD

**Issue by ConneXNL** [greypants/gulp-starter#126]
Is this setup supposed to generate source map files? Before I found this library I used this configuration for browserify:
https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md

In order to get the source maps to show up I added the following to the browserify task:

At the top I added:

        var sourcemaps = require('gulp-sourcemaps');
        var buffer = require('vinyl-buffer');
        var gulpif = require('gulp-if');

After .pipe(source(bundleConfig.outputName)) I added:

        // optional, remove if you don't need to buffer file contents
        .pipe(gulpif(devMode, buffer()))

        // optional, remove if you dont want sourcemaps
        .pipe(gulpif(devMode, sourcemaps.init({loadMaps: true}))) // loads map from browserify file

        // Add transformation tasks to the pipeline here.
        .pipe(gulpif(devMode, sourcemaps.write('./'))) // writes .map file

Am I missing something? I am using livereload instead of browserSync, is that the reason?

**Comment by greypants** [comment]
I if I remember right, I'm using inline source maps - and I always write them. They get stripped out in the production task when comments are removed. Did you clone and run this, and you're not seeing source maps in devtools? Or are you just looking at the code and trying to figure out how it works?

**Comment by greypants** [comment]
Here's the line that enables js sourcemaps (and yeah, they're inline) https://github.com/greypants/gulp-starter/blob/master/gulp/tasks/browserify.js#L28

and for Sass, I guess maybe I am generating files:
https://github.com/greypants/gulp-starter/blob/master/gulp/tasks/sass.js#L11-L14
