### ISSUE TITLE
Seperate config files?

### ISSUE THREAD

**Issue by ConneXNL** [greypants/gulp-starter#131]
I have a project in where I need two seperate config files. Also, I want to reuse the tasks as they are project independent where the config is not.

However, since all the tasks this gulp-starter provides all use config files relative to the task's directory, makes it really hard to re-use these tasks.

Wouldn't it be a better option to pass in the configuration to a task via require, or use a global object, or some kind of singleton configuration object?

**Comment by greypants** [comment]
They're separated out in the 2.0 branch, but that has it's issues too. But I agree, I think it's a little better.
