### ISSUE TITLE
returning tasks

### ISSUE THREAD

**Issue by tucsonlabs** [greypants/gulp-starter#132]
Why are you returning tasks rather than running them. For example in the sass task you have:

```
gulp.task('sass', function () {
  return gulp.src(config.src)
  ...
```

It seems to work fine without returning like so:
```
gulp.task('sass', function () {
  gulp.src(config.src)
  ...
```

What's the reason for this?

**Comment by greypants** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/API.md#return-a-stream

Returning a stream enables Gulp to listen for the task to actually complete. This is important when one task relies on another to have finished.

**Comment by tucsonlabs** [comment]
Thanks for the explanation.

**Comment by greypants** [comment]
:+1:
