### ISSUE TITLE
shared.js - how to add some shared js?

### ISSUE THREAD

**Issue by rstormsf** [greypants/gulp-starter#135]
Can somebody explain how does this work:

```
 webpackConfig.plugins.push(
      new webpack.optimize.CommonsChunkPlugin({
        name: 'shared',
        filename: env === 'production' ? '[name]-[hash].js' : '[name].js',
      })
    )
```
where does the `name` come from?

I mean, I see entries:

```
    entry: {
      page1: [jsSrc + 'page1.js'],
      page2: [jsSrc + 'page2.js']
    },

```
but where is `shared.js` entry defined?

where is the place where I define what should be in `shared.js` I see this file is generated, but no understanding where is the code that reads that info

**Comment by rstormsf** [comment]
Figured it out -
Basically, I have to duplicate code in `page1.js` and `page2.js` like
```
let bs = require('bootstrap')`
```
in both files, it will figure it out automatically and create `shared.js` based on common dependencies in both files

**Comment by greypants** [comment]
:+1: Exactly. Webapack automatically fills it with shared dependencies (vs having to manually create one). Really useful if you've got a big site with a mix of page specific js and globally used libraries or helper methods. Include shared.js on every page - and page specific files on their respective pages.  On a smaller project, it's probably unnecessary, but I have it hear just as an example.
