### ISSUE TITLE
v2.0 - How to add CoffeeScript and jQuery?

### ISSUE THREAD

**Issue by voodee** [greypants/gulp-starter#138]

**Comment by soenkekluth** [comment]
Please no! ES6 is fine!

**Comment by greypants** [comment]
`npm install jquery --save`
`npm install coffee-loader --save`

https://github.com/webpack/coffee-loader

**Comment by greypants** [comment]
As much as I loved Coffee, the web is moving towards es6, and there's a lot of benefit. That said, I really do miss indented syntax, and the lack of extraneous characters.
