### ISSUE TITLE
Isn't requiring modules in every task a bad thing?

### ISSUE THREAD

**Issue by Djuka** [greypants/gulp-starter#146]
As I understand, every time you do a require, directories are searched for a module. If every task has:

```javascript
    var gulp = require('gulp');
```

wouldn't that just make gulp load more than once in just different scope? I am quite new to Node. Hope to get some explanation.

**Comment by greypants** [comment]
nope. The way `require` works is that it only pulls in the code once, and then just refers to a saved reference after that.

Here's a little more explanation about how modules work: https://github.com/greypants/gulp-starter/wiki/What-is-a-Module%3F
