### ISSUE TITLE
How stable is v2.0?

### ISSUE THREAD

**Issue by erwingeiger** [greypants/gulp-starter#148]
Can I use it for production? Or is it better to still use the master?

**Comment by DJTB** [comment]
It's been working just fine for me.

*I'm not a maintainer though

**Comment by greypants** [comment]
Pretty stable - depending on your environment, you may have to tweak or fix a couple things, but I've been using it for months. The main thing that's missing is just a README. Check github issues for known issues. But 2.0 is way better. Go for it.

**Comment by jefsnare** [comment]
@greypants Could you be specific about 'you may have to tweak or fix a couple things' ?

Anyone has worked with bower in combination with gulp-starter / webpack?

**Comment by greypants** [comment]
@jefsnare You may have to tweak or change things depending on your folder structure and project requirements. This repo is just meant to be a starting point for you to build on. It works great as-is, but to integrate it into another tech stack, you'll likely have to make some modifications, and may have to address edge cases I haven't handled.

**Comment by greypants** [comment]
Merging soon, and will tag as a release
