### ISSUE TITLE
dealing with warnings - mocha - fsevents - webpack

### ISSUE THREAD

**Issue by dkebler** [greypants/gulp-starter#153]
Not fatal (yet) but how can I deal with these warnings?  First two appear in master branch and all three in 2.0 branch.  I am running .12 node (on ubuntu 14.10) and have no intention of reverting to earlier version.  

````
npm WARN engine karma-cli@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.8.4"})
npm WARN peerDependencies The peer dependency mocha@* included from karma-mocha will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN engine svg-pathdata@1.0.0: wanted: {"node":"0.10.*"} (current: {"node":"0.12.2","npm":"2.8.4"})
npm WARN peerDependencies The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6
````

**Comment by greypants** [comment]
from what I understand, peerDependencies are going away in npm 3. Module authors using them will need to let their users know to manually add any peer dependencies to their package.json file. That would take care of the peerDependency warnings.

The first warning is just saying the author hasn't explicitly specified that Karma will work with 0.12.x. It works fine though. Warning should eventually go away when the author updates the node engines list.

 The other ones are misc warnings more for the author than for the user. I wouldn't worry about them.
