### ISSUE TITLE
Swig is no longer maintained :(

### ISSUE THREAD

**Issue by nhunzaker** [greypants/gulp-starter#154]
Womp womp :( https://github.com/paularmstrong/swig/issues/628

**Comment by greypants** [comment]
fun!

**Comment by mikeerickson** [comment]
@greypants provided you don't want to do rending on the server.

**Comment by code-chimp** [comment]
Nunjucks appears to work for me - https://gist.github.com/code-chimp/a2e67cad2a282b68c426

I name my folder layout is slightly different, but the same spirit applies.

**Comment by greypants** [comment]
Addressed in 2.0 (switched to nunjucks)
