### ISSUE TITLE
"Error: task is not defined" after npm update

### ISSUE THREAD

**Issue by VincentLahaye** [greypants/gulp-starter#157]
Hi !

I've been using the v2 branch for one of my project.
Working nice so far !

But after a `sudo npm update`, when I `gulp`, it tells me :
```Error: task "clean" is not defined```

the `clean` task is the first one. If I comment it from `build:development`, then the same error shows for the `font` task.

And when I run `gulp clean`, everything works fine !

Any help would be appreciated. Cheers !

**Comment by VincentLahaye** [comment]
I've just started a clean project and rewrote the gulp logic.
Thanks anyway ! :)

**Comment by greypants** [comment]
Weird! I'll keep an eye out and see if this pops up for me
