### ISSUE TITLE
wrong publicPath?

### ISSUE THREAD

**Issue by newtonianb** [greypants/gulp-starter#160]
I don't understand why publicPath is set to ``var publicPath = 'assets/javascripts/'``
Shouldn't it be the output directory?

https://github.com/greypants/gulp-starter/blob/2.0/gulpfile.js/config/webpack.js#L9

This is causing a problem for me when I compile fonts with webpack, it tries to find the font in the publicPath which in this case is assets/javasripts but that's not accessible when the app is compiled in ``public``

**Comment by greypants** [comment]
Hm. I could totally have that wrong. I'll re-look at the docs, and see if everything still compiles right with your suggestion. Thanks.

**Comment by greypants** [comment]
So looking into it, I think I have it right. `publicPath` should be set to the location of your bundled JS relative to your site. `output.path` is relative to your project.

Not sure how you might need to move around files or directories to compile fonts with webpack. That's probably out of scope for this project—I'm still handling fonts and non-js assets with Gulp, and decided to only let Webpack care about JS.

Let me know if you get things working how you wanted, and what you changed though.
