### ISSUE TITLE
Use the `paths` option of browserify to avoid relative paths hell

### ISSUE THREAD

**Issue by slorber** [greypants/gulp-starter#17]
Based on your project, I've build some starter app structure (that I'll publish soon), to create Phonegap/Cordova apps using Gulp / Browserify / React...

What really bothered me with your project was the fact that in our app, the browserify components we create could not be required using module style but only relative paths.

This leads to things like `require("./../../../../MyModule") which is a real pain when we refactor, move files and need our brain to think about how much nesting we need or things like that...

One solution to this problem is to use the `paths` option of browserify.

In my case, I have just added some `/js/` folder to this `paths`, because it is the folder in which I put all js files I develop:

```
    return browserify({
        entries: ['./src/js/app.js'],
        extensions: ['.jsx'],
        paths: ['./node_modules','./src/js/']
    })
        .transform('reactify')
        .bundle({debug: true})
        .on('error', handleErrors)
        .pipe(source('app.js'))
        .pipe(gulp.dest('./www'));
```

(for an unknown reasons, I had to put the `./node_modules` or it wouldn't work, I opened some bug for that)

This way, instead of doing `require("./../../common/MyUtil")` or `require("./../../../../../common/MyUtil")` based on where I am currently in the path, I can simply do `require("common/MyUtil")` everywhere in my code.

Another option is that the build file can find all subdirectories of the `/js/` directory and then add them all to the path, like shown here: https://gist.github.com/sbrekken/05937e81927802452f48

This way one can simply use `require("MyUtil")`
(maybe in this case it would worth trying to see how browserify handle naming conflicts in case your own filename already matches an existing npm module)

**Comment by greypants** [comment]
Moved to webpack, so closing this out. The option in webpack is: [resolve-modulesdirectories](http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories)

**Comment by slorber** [comment]
By chance is it explained somewhere why you choose to replace browserify with webpack?

**Comment by greypants** [comment]
Blog post forthcoming perhaps. In short, it's way more powerful. You can output multiple bundles, extract shared dependencies into a shared bundle, async module loading is silly easy, it's smart about dynamic requires, and more. Been using it for almost a year now and haven't looked back.

**Comment by rjdlee** [comment]
I'm having issues with babelify caching my src/node_modules files, does anyone know how to get around that?

**Comment by waspa** [comment]
hjk

**Comment by Dimes** [comment]
Is there a command line version of this?

**Comment by Heliodromel** [comment]
Hello, i'm also looking for a command line version for this path option. Any tips ?

**Comment by slorber** [comment]
yes @Heliodromel it's just and env variable
