### ISSUE TITLE
error in npm run production

### ISSUE THREAD

**Issue by jitendravyas** [greypants/gulp-starter#175]
When i run `npm run production`

I get below error

```
▶ npm run production
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "production"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! missing script: production
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jitendra.vyas/projects/ola/money-landing/npm-debug.log
```

**Comment by greypants** [comment]
Are you on the 2.0 branch?

**Comment by greypants** [comment]
The error means the task doesn't exist. Looks like you might be in the wrong branch. `git checkout 2.0` then try.

**Comment by shivangbtech** [comment]
getting error:


fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


when use git checkout 2.0 to solve error in npm run production

**Comment by greypants** [comment]
2.0 was merged a while ago, and the branch no longer exists.. `npm run production` is in `master` now.

**Comment by shivangbtech** [comment]
I am getting error while running 'sudo npm run production'

npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "production"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! missing script: production
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ttnd/github-battle/npm-debug.log



How to solve out

**Comment by shivangbtech** [comment]
I got the solution command will be 'sudo npm run prod'

**Comment by greypants** [comment]
You should never need sudo to run npm commands. See the following to fix permissions:

http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo
https://docs.npmjs.com/getting-started/fixing-npm-permissions
