### ISSUE TITLE
Version 2.0 rev-assets path is not configurable

### ISSUE THREAD

**Issue by benjtinsley** [greypants/gulp-starter#184]
https://github.com/greypants/gulp-starter/blob/2.0/gulpfile.js/tasks/rev/rev-assets.js#L16

should this be based off publicDirectory rather than absolute path using '/public'?

**Comment by greypants** [comment]
good catch! Thanks.

**Comment by greypants** [comment]
JK! Addressed this yesterday in https://github.com/greypants/gulp-starter/pull/182

Mergin' soon.

**Comment by greypants** [comment]
Fixed in #182
