### ISSUE TITLE
watch calls not found 'js' task

### ISSUE THREAD

**Issue by MariusRumpf** [greypants/gulp-starter#187]
When changing a javascript file, the watch task calls the task js which is non existent. 
Changing the line in `gulpfile.js/tasks/watch.js`
```js
  var watchableTasks = ['fonts', 'iconFont', 'images', 'svgSprite','html', 'css', 'js']
```
to 
```js
  var watchableTasks = ['fonts', 'iconFont', 'images', 'svgSprite','html', 'css']
```
solves the issue for me. Javascript is then compiled with webpack-watch again.

Branch: 2.0

**Comment by greypants** [comment]
oh good catch! Thanks. On it!

**Comment by MariusRumpf** [comment]
Thank you, keep up the good work!
