### ISSUE TITLE
Compass source maps not found

### ISSUE THREAD

**Issue by kitx** [greypants/gulp-starter#49]
SASS source maps work fine with my own files, but I get a 404 errors in the console for all the Compass imported SASS sheets.

For example:
http://localhost:3000/sass/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems….1.0/gems/compass-core-1.0.0.rc.1/stylesheets/compass/css3/_transform.scss

Which obviously can't be found. This is the default project, what's going wrong here?

**Comment by greypants** [comment]
Closing this since I removed the compass dependency. Libsass + autoprefixer is totally worth it!

**Comment by kitx** [comment]
Agreed, works beautifully now.
