### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by adyz** [greypants/gulp-starter#52]
Hi guys, 

I've used this pack two months ago and it was all about gulp and I had a really nice baseline to start, nothing to remove, just things to add that I could find myself. Now it's all crazy.

Gulp starter should be for starting a new project independent of JS frameworks and workflows. 

To much stuff to remove and it's too opinionated.

BrowserSync does the refresh, why support for LiveReload too?

Handlebars
Npm backbone
Npm jquery
Underscore (included with Backbone)

Why all these? I use angular.js for some projects too, so, if that, I need to remove handlebars from the project.

I really loved the initial builds of this project, but now it looks overwhelming.

**Comment by greypants** [comment]
Use https://github.com/greypants/gulp-starter/issues/97 for further feedback.
