### ISSUE TITLE
Manage external bundles

### ISSUE THREAD

**Issue by ebrehault** [greypants/gulp-starter#57]
I try to package all my vendors libraries (like angular, declared in my package.json `browserify-shim` section) in a bundle and my app specific js in another bundle.
Of course, the vendors libs must be declared as external in my app bundle.
To do that, I have added an `externals` param to `bundleConfigs` in config.js, and I have changed the `browserify` task like this:
```
if(bundleConfig.externals) {
    bundler
        .require(bundleConfig.externals)
        .external(bundleConfig.externals);
}
```
I would be happy to propose a pull-request for that, but right now, it does not work: I cannot require my vendors libs from my app scripts.
Am I supposed to call [transform()](https://github.com/substack/node-browserify#btransformtr-opts) ?

**Comment by ieugen** [comment]
Any updates on this? 

I'm working on a gulp-starter project and  "bundleConfigs require" does not work for "gulp production" with bower components exposed via browserify-shim. 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'jquery' from '/project/'
    at /.../node_modules/browserify/node_modules/resolve/lib/async.js:50:17
    at process (/.../node_modules/browserify/node_modules/resolve/lib/async.js:
```

**Comment by greypants** [comment]
@ieugen #67 addressed this issue. In your error it looks like there's some path issues going on there. I'd double check those first, but I'm not familiar with `bower` and `debowerify`. This isn't a direct answer, but why not install jquery from npm? You shouldn't need to debowerify or shim jquery.
