### ISSUE TITLE
Sass slows down quite a bit with this approach

### ISSUE THREAD

**Issue by lmartins** [greypants/gulp-starter#70]
For some reason Sass compilation slows down quite a bit with this approach to organize Gulp Tasks.
For the same project I get using gulp-starter:

```
[BS] 2 files changed (editor.css, main.css)
[gulp] Finished 'sass' after 558 ms
[gulp] Starting 'sass'...
```

and without it:
```
[gulp] Starting 'sass'...
[gulp] Finished 'sass' after 5.05 ms
[BS] 2 files changed (editor.css, main.css)
```
Removing source maps and autoprefixer from the gulp-starter sass tasks seem to do no difference.

Any ideia why this might be happening? Could it be the task loader running through the task files?

**Comment by adyz** [comment]
Hi Guys, 

I have the same problem. 


This is happening on other BrowserSync/Gulp setup, even the one recommended on BrowserSync website.
I also tried to remove autoprefixer & other pipes, but still getting injected all the main scss files.

**Comment by lmartins** [comment]
After further testing i've came to the conclusion that is the access to the config file within the tasks that is slowing everything down.

Removing the references to "source", "build" and plugin configuration from the sass task everything goes back to normal values, including the autoprefixer and sourcemaps tasks.

**Comment by greypants** [comment]
Are you guys returning the streams in your tasks? 5.05 ms seems impossibly fast - like that the task is reporting finished as soon as it runs, instead of as soon as the sass is finished compiling.

**Comment by greypants** [comment]
Also, I pushed up some [changes to the BrowserSync implementation](https://github.com/greypants/gulp-starter/commit/1466eee867271271d91d7f837a1291c40e139fa3) over the weekend. Let me know if your issues persist with the new setup.

**Comment by lmartins** [comment]
Hey Dan,
Thanks for the updates, i'll test them asap. 
Regarding the compilation times, I can assure you the difference is quite noticeable. With my "common" gulp file the compilation is pretty much instant.

**Comment by lmartins** [comment]
Hi Dan, im closing this one since it seems there's nothing to do here.
One quick note though. I've noticed on my setup that returning the task does add about 1s to each compilation, that is:

```
gulp.task('sass-build', function () {
  gulp.src( config.SASS.src )
```
vs this:
```
gulp.task('sass-build', function () {
  return gulp.src( config.SASS.src )
```

**Comment by greypants** [comment]
@lmartins Cool, thanks. So when you don't return the task, gulp will immediately report that the task has finished, regardless of whether or not the file has finished compiling. [You *must* return a stream, or fire a callback if you want proper task reporting.](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support) Otherwise gulp has no way of knowing when it's complete, and immediately moves on to the next thing.
