### ISSUE TITLE
SASS complains with non-quoted @imports

### ISSUE THREAD

**Issue by tommymarshall** [greypants/gulp-starter#76]
![screen shot 2015-01-20 at 10 55 08 am](https://cloud.githubusercontent.com/assets/871454/5820443/fb1b53fe-a092-11e4-8ed8-46f804e131c2.png)

Adding quotes around files being `@import`ed withing `app.sass` fixes this issue.

**Comment by ieugen** [comment]
same here

**Comment by greypants** [comment]
Looks like `gulp-sass` has a couple breaking updates, including this one: https://github.com/dlmanning/gulp-sass/issues/173

I'll address. Thanks guys.

**Comment by greypants** [comment]
Found the culprit! https://github.com/sass/node-sass#indentedsyntax new `indentedSyntax` option! No more hacky workaround needed.
