### ISSUE TITLE
Cannot find module 'underscore' when running gulp production

### ISSUE THREAD

**Issue by askesian** [greypants/gulp-starter#87]
I get the following error when running the production build
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'underscore' from '/Users/Chris/Projects/gulp-starter'
```
Do you not get this error when you run the production gulp task?

**Comment by ieugen** [comment]
maybe you have corrupted modules? try removing *node_modules* folder and do *npm install* again

**Comment by askesian** [comment]
After a bit of testing, I determined that this error occurs if I do not have underscore installed as node_module on it's own. If I do simple checkout of this repo, run `npm install` and then do `gulp production` the error occurs. If I run `npm install -D underscore`, and then run `gulp production`, the project builds with no errors. On the other hand, if I do not install `underscore` as it's own module, but instead replace this line in the config.js:

```
require: ['jquery', 'underscore']
```

with:

```
require: ['jquery', 'backbone/node_modules/underscore']
```
the build completes successfully.

So, am I doing something else wrong with regard to the loading of `underscore`? Because, for me, it appears that I either need to have `underscore` installed as it's own module (e.g., do not rely on `underscore` within `backbone` module dependencies), or I have to explicitly specify the path to `underscore` within the `backbone` dependencies, when specifying the `require`-ed assets.

I referenced this during my troubleshooting: https://github.com/substack/node-browserify#brequirefile-opts

**Comment by greypants** [comment]
Yeah, I saw this happen to a friend at work, but I couldn't replicate it on my machine. Might have something to do with minor version differences. Either way, I'll definitely look into it.

**Comment by askesian** [comment]
Thanks for the reply. I've run my starter kit (which borrows liberally from your examples here - thanks!!!) on several Macs and Windows machines, and everything is cool as long as I use `backbone/ode_modules/underscore` in the require param array, so I'm going to stick with that for now. The main thing is that I know that it works. Thanks again for all your efforts putting your repo together. It has been immensely helpful.

**Comment by greypants** [comment]
:+1:

**Comment by greypants** [comment]
Was able to reproduce it after upgrading node and npm, killing my node_modules folder and running `npm cache clean`. Pushed up the fix you suggested with a note linking to this issue. Thanks! 

Eventually I need to remove that backbone/underscore example. I think it's more confusing than helpful at this point. Maybe move a note about that edge case into the wiki instead.

**Comment by alpgumus** [comment]
Got this resolved by fixing the path of underscore in packages.json:
```
"underscore": "./node_modules/backbone/node_modules/underscore",
```
