### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by arlo-j** [greypants/gulp-starter#89]
Great starter kit, but one issue I've run into is after running `gulp production` with no errors, I try to run the contents of /build in browser and get `Uncaught Error: Cannot find module 'underscore'`.

Help?

**Comment by greypants** [comment]
Have you pulled in the last couple days? This was issue #87 - it should be fixed in this commit from a couple days ago: https://github.com/greypants/gulp-starter/commit/8ab54ca940ad5e46896811c6ca352a5d3c2c1259

Lemme know if you're still having issues since that update.

**Comment by arlo-j** [comment]
I pulled the latest version, and now get this (completely fresh project, no modifications) when running `npm install`:

`module.js:340
    throw err;
          ^
Error: Cannot find module './fs.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)`

**Comment by arlo-j** [comment]
Further notes, this is apparently an issue with two conflicting installs of Node.  Not to do with your code (but maybe handy in case someone runs into it in the future).  Wierd that this didn't happen last week when I didn't encounter this error... haven't done anything different since then.

https://github.com/npm/npm/issues/6348#issuecomment-57233553

**Comment by arlo-j** [comment]
Conclusive notes: still have console error 'cannot find module "underscore"' after running index.html within build following 'gulp production.'

**Comment by greypants** [comment]
Hmm. I'll reopen for now until I can look into this further. I recommend using [nvm](https://github.com/creationix/nvm) for managing multiple versions of node if you're not already.

**Comment by greypants** [comment]
Underscore is no longer a dependency in 2.0 (merging soon)
