### ISSUE TITLE
tsify

### ISSUE THREAD

**Issue by yilativ** [greypants/gulp-starter#92]
Hi all, 
I am at a loss how I'd add a new plugin TSIFY (akin to coffee script) into this gulp starter pipeline. 

Has anyone integrated typescript with this starter?

Thanks

**Comment by greypants** [comment]
Just add it to the [browserify `transform` list in package.json](https://github.com/greypants/gulp-starter/blob/master/package.json#L24)

**Comment by yilativ** [comment]
I did that, but it looks like it did not work as the tsify plugin received just the string (my main.ts file path) instead of the stream or whatever object it expected. 

So what I did was this in the browserify.js: 
``` 
if (bundleConfig.plugins && b.plugin) {
                for (var pluginName in bundleConfig.plugins) {
                    var pluginSettings = bundleConfig.plugins[pluginName];
                    b.plugin(pluginName, pluginSettings);
                    console.log(pluginSettings);
                }
            }
```

and in my config.js: 
```
bundleConfigs: [
            // Application
            {
                entries: [src + "/app.ts"],
                dest: dest,
                outputName: 'app.js',
                extensions: ['.ts', '.js'],
                plugins: {
                    "tsify": {
                        //Warn on expressions and declarations with an implied any type.
                        noImplicitAny: true,

                        //Do not emit comments to output.
                        removeComments: true,

                        //Specify ECMAScript target version: 'ES3' (default), or 'ES5'
                        target: "ES5",
                    }
                },
            }
        ]
```

That made it work, otherwise this is the code that would throw the exception because <c>b</c> is not whatever that object is but just a string: 
```
	if (b._extensions.indexOf('.ts') === -1)
```

Not sure if that helps out anybody but that's how I ended up making this starter work. 

Thanks for the hard work by the way!

**Comment by greypants** [comment]
Oooohh... it's a plugin, not a transform. Got it. Looks good! I should add that to mine as well. I'll open an issue to support plugins from the config.

**Comment by yilativ** [comment]
Awesome!! Thank you kind sir!

**Comment by morlay** [comment]
sometimes we need  `bundle-collapser`, too.
