### ISSUE TITLE
package.json issue on browserify update

### ISSUE THREAD

**Issue by magus** [greypants/gulp-starter#95]
It seems like on update the bundle process adds an unnecessary 'module.exports=' piece to the beginning of the package.json files of any dependent modules. It isn't immediately obvious to me if this is a bug in the browserify.js gulp task, browserify or watchify, but I believe it lies in one of those three things.

You can easily reproduce this issue by adding something like `require('bitcore')` to the index.js file, running gulp and then triggering an update by modifying a file.
![screen shot 2015-02-15 at 7 55 54 pm](https://cloud.githubusercontent.com/assets/290084/6207031/b4eaad84-b54c-11e4-895f-718df30348fd.png)

**Comment by magus** [comment]
https://github.com/substack/node-browserify/issues/1101

Looks like a known issue in browserify.

**Comment by greypants** [comment]
Cool - looks like it was just fixed. I'll update the dependency and close this soon.
